services:
  - type: web
    name: online-voting-system
    runtime: docker
    plan: starter
    region: oregon
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_TIMEZONE
        value: Africa/Nairobi
      - key: EVOTE_HASH_SECRET
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
